combine_control_expr = false
fn_params_layout = "Vertical"
force_multiline_blocks = true
format_strings = true
imports_layout = "Vertical"
group_imports = "StdExternalCrate"
tab_spaces = 4
unstable_features = true
use_try_shorthand = true
