[package]
name = "kansei-parser"
version = "0.1.0"
authors = ["Danilo Spinella <oss@danyspin97.org>"]
edition = "2018"

[dependencies]
kansei-core = { path = "../core" }
futures = "0.3.21"
nix = "0.23.1"
snafu = { version = "0.7.0", features = ["futures"] }
tokio = "1.17.0"
