[package]
name = "rinit-parser"
version = "0.1.0"
authors = ["Danilo Spinella <oss@danyspin97.org>"]
edition = "2021"

[dependencies]
rinit-service = { path = "../service" }
nix = "0.24.2"
snafu = "0.7.1"
snailquote = "0.3.1"
