[package]
name = "rinit-ipc"
version = "0.1.0"
edition = "2021"

[dependencies]
rinit-service = { path = "../service" }
lazy_static = "1.4.0"
nix = "0.24.1"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
snafu = "0.7.1"
